insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('morbi', 92.17, 15.47, 26.78, 96.45, 95.03, 'nibh');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('tristique', 87.73, 3.57, 11.74, 1.05, 98.79, 'aliquet');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('parturient', 54.46, 55.07, 20.41, 77.58, 96.71, 'etiam');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('mauris', 94.39, 88.93, 50.87, 37.51, 11.63, 'hac');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('sapien', 83.55, 32.14, 9.52, 61.58, 5.57, 'diam');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('quis', 73.31, 82.73, 98.02, 25.02, 5.57, 'tincidunt');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('pulvinar', 74.2, 49.11, 54.73, 90.32, 39.29, 'vestibulum');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('lacinia', 11.27, 97.93, 53.65, 27.74, 61.11, 'consequat');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('suspendisse', 76.57, 92.81, 26.93, 29.26, 76.06, 'donec');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('mauris', 63.29, 80.74, 81.83, 37.35, 43.97, 'pellentesque');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('dignissim', 34.47, 18.22, 8.82, 93.54, 71.87, 'nisi');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('vel', 90.79, 35.13, 31.91, 65.06, 45.76, 'felis');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('purus', 23.6, 44.12, 50.25, 85.96, 26.68, 'eu');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('nulla', 42.95, 37.26, 80.37, 72.05, 78.34, 'id');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('volutpat', 54.49, 11.87, 61.94, 39.13, 26.75, 'vulputate');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('elementum', 87.4, 25.32, 59.93, 5.39, 83.41, 'ipsum');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('diam', 2.46, 29.57, 84.67, 98.92, 56.25, 'in');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('cras', 83.13, 88, 48.79, 18.26, 42.15, 'vestibulum');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('nunc', 79.45, 81.02, 68.64, 98.08, 50.1, 'mauris');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('augue', 13.2, 70.54, 11.27, 40.04, 70.9, 'potenti');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('neque', 81.65, 35.17, 51.87, 49.09, 47.77, 'tristique');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('et', 70.55, 81.77, 71.5, 99.09, 95.4, 'pede');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('pede', 85.58, 50.73, 1.75, 18.42, 69.49, 'aenean');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('justo', 99.16, 20.95, 89.49, 7.06, 67.35, 'odio');
insert into spaceObject (name, radius, mass, EarthDistance, age, rotationSpeed, galaxyName) values ('duis', 88.41, 85.02, 26.85, 52.91, 64.12, 'felis');

insert into star (starType, color) values ('est', 'morbi');
insert into star (starType, color) values ('porta', 'tellus');
insert into star (starType, color) values ('turpis', 'maecenas');
insert into star (starType, color) values ('curabitur', 'proin');
insert into star (starType, color) values ('velit', 'posuere');
insert into star (starType, color) values ('vivamus', 'sed');
insert into star (starType, color) values ('non', 'posuere');
insert into star (starType, color) values ('facilisi', 'vestibulum');
insert into star (starType, color) values ('feugiat', 'erat');
insert into star (starType, color) values ('porta', 'ipsum');
insert into star (starType, color) values ('vitae', 'dui');
insert into star (starType, color) values ('luctus', 'fusce');
insert into star (starType, color) values ('accumsan', 'sem');
insert into star (starType, color) values ('suspendisse', 'blandit');
insert into star (starType, color) values ('a', 'etiam');
